http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: 
      - '/ip'  
      - '/api/*'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  pds:
    url: 'https://api.partiudoarsangue.com.br'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: pds
    apiEndpoints:
      - api
    policies:
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: pds
              changeOrigin: true