http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: 
      - '/ip'              
  pds: 
    host: localhost
    paths: 
      - /pds/*
  ezl: 
    host: localhost
    paths:  
      - /ezl/*
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  pds:
    url: 'https://api.partiudoarsangue.com.br'
  ezl: 
    url: 'https://ezl.ezlawyer.com.br'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite

pipelines:
  pds:
    apiEndpoints:
      - pds
    policies:
      - rewrite: 
        - condition: 
            name: regexpmatch
            match: ^/pds/(.*)$
          action:
            rewrite: /api/$1
      - proxy:
          - action:
              serviceEndpoint: pds
              changeOrigin: true
  ezl:
    apiEndpoints:
      - ezl
    policies:
      - rewrite: 
        - condition: 
            name: regexpmatch
            match: ^/ezl/(.*)$
          action:
            rewrite: /api/v1/$1
      - proxy:
          - action:
              serviceEndpoint: ezl
              changeOrigin: true